title: 
description: This project aims to provide insights and recommendations for fostering effective technical communication within agile development teams.
theme: just-the-docs

url: https://Nataziet.github.io/Developing-Effective-Technical-Communication-Strategies-for-Agile-Development-Teams


color_scheme: dark

logo: "/Developing Effective Technical Communication Strategies for Agile Development Teams\Developing-Effective-Technical-Communication-Strategies-for-Agile-Development-Teams\images\TechWR_Icon.png"